
.PHONY: all clean

PROJECT_NAME = TestConverter

# BUILD_MODE = RELEASE
BUILD_MODE := DEBUG

# Default to MacOSX, ymmv
PLATFORM_OS = OSX
# PLATFORM_OS = WINDOWS
# PLATFORM_OS = LINUX

# Define default make program: Mingw32-make
MAKE = mingw32-make

# Define default C compiler: gcc - on Windows use mingw
# NOTE: define g++ compiler if using C++
CXX = g++


CXXFLAGS = -Wall -std=c++20 -stdlib=libc++
INCLUDE_PATHS = -I.

## For now no dependent libs
LDFLAGS :=
LDLIBS :=

ifeq ($(PLATFORM_OS),LINUX)
	MAKE = make
	INCLUDE_PATHS += -isystem. 
endif

ifeq ($(PLATFORM_OS),OSX)
	MAKE = make
	CXX = clang++
endif

ifeq ($(BUILD_MODE),DEBUG)
	CXXFLAGS += -g -O0
else
	CXXFLAGS += -s -O1
endif

SRCS = $(wildcard *.cpp)
OBJS = $(patsubst %.cpp, %.o, $(SRCS))

depend: Makefile.dep
	$(CXX) -MM $(SRCS) > Makefile.dep

all:
	$(MAKE) $(PROJECT_NAME)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDE_PATHS) -c $< -o $@

$(PROJECT_NAME): $(OBJS)
	$(CXX) -o $(PROJECT_NAME) $(LDFLAGS) $^ $(LDLIBS) -o $@


# Clean everything
clean:
ifeq ($(PLATFORM_OS),WINDOWS)
	del *.o *.exe /s
endif
ifeq ($(PLATFORM_OS),LINUX)
find -type f -executable | xargs file -i | grep -E 'x-object|x-archive|x-sharedlib|x-executable' | rev | cut -d ':' -f 2- | rev | xargs rm -fv
endif
ifeq ($(PLATFORM_OS),OSX)
	find . -type f -perm +ugo+x -delete
	rm -f *.o
endif

-include $(DEPFILES)