# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/ue4/UnrealEngine

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Development  \
	UnrealClient-Linux-Shipping  \
	UnrealClient \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Development  \
	UnrealServer-Linux-Shipping  \
	UnrealServer \
	AdventureTemplate-Linux-DebugGame  \
	AdventureTemplate-Linux-Development  \
	AdventureTemplate-Linux-Shipping  \
	AdventureTemplate \
	AdventureTemplateEditor-Linux-DebugGame  \
	AdventureTemplateEditor-Linux-Development  \
	AdventureTemplateEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend AdventureTemplateEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug AdventureTemplateEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  $(ARGS)

UnrealClient-Linux-Development:
	 $(BUILD) UnrealClient Linux Development  $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  $(ARGS)

UnrealClient: UnrealClient-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  $(ARGS)

UnrealServer-Linux-Development:
	 $(BUILD) UnrealServer Linux Development  $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  $(ARGS)

UnrealServer: UnrealServer-Linux-Development

AdventureTemplate-Linux-DebugGame:
	 $(BUILD) AdventureTemplate Linux DebugGame  -Project="/project/AdventureTemplate.uproject" $(ARGS)

AdventureTemplate-Linux-Development:
	 $(BUILD) AdventureTemplate Linux Development  -Project="/project/AdventureTemplate.uproject" $(ARGS)

AdventureTemplate-Linux-Shipping:
	 $(BUILD) AdventureTemplate Linux Shipping  -Project="/project/AdventureTemplate.uproject" $(ARGS)

AdventureTemplate: AdventureTemplate-Linux-Development

AdventureTemplateEditor-Linux-DebugGame:
	 $(BUILD) AdventureTemplateEditor Linux DebugGame  -Project="/project/AdventureTemplate.uproject" $(ARGS)

AdventureTemplateEditor-Linux-Development:
	 $(BUILD) AdventureTemplateEditor Linux Development  -Project="/project/AdventureTemplate.uproject" $(ARGS)

AdventureTemplateEditor: AdventureTemplateEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/project/AdventureTemplate.uproject" -Game 

.PHONY: $(TARGETS)
