name: Unreal Engine Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:
    # Containers require a Linux-based runner host
    runs-on: ubuntu-latest
      
    container:
      # Requires membership of the Epic Games Github organisation and acceptance of the Terms
      # https://github.com/orgs/epicgames/packages/container/unreal-engine/492471794?tag=dev-5.6.1
      # Note that here I use a specifically created PAT with access only to the packages, the PAT has 
      # no privileges to operate on any of the rest of my github. I add that to the secrets manager
      # in github, along with the username I access github with. By doing this I avoid the need to 
      # add the 
      #   `permissions: packages`
      # that is required if using the GitHub supplied vars - https://stackoverflow.com/a/78866108/813919
      image: ghcr.io/epicgames/unreal-engine:dev-slim-5.6.1
      credentials:
        username: ${{ secrets.GHCR_IO_USERNAME }}
        password: ${{ secrets.REPO_ACCESS_TOKEN }}
      options: --user root
      volumes:
        - /project

    steps:
      - name: AdventureGameTemplate checkout code
        uses: actions/checkout@v6.1.0
        with:
          lfs: true

      - name: PaperZD checkout code
        uses: actions/checkout@v6.1.0
        with:
          repository: heavybullets/PaperZD
          path: Plugins
          ref: v2.2.4

      - name: Build project
        run: |
          pwd && env && ls -l -a
          sed -i 's/"EngineVersion":.*/"EngineVersion": "5.6.0",/g' Plugins/PaperZD/PaperZD.uplugin
          ./Scripts/Build.sh

      - name: Tests
        run: |
          ./Scripts/Test.sh
          
