name: Unreal Engine Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:
    # Containers require a Linux-based runner host
    runs-on: ubuntu-latest
      
    container:
      image: ghcr.io/epicgames/unreal-engine:dev-slim-5.6.1
      credentials:
        username: ${{ secrets.GHCR_IO_USERNAME }}
        password: ${{ secrets.REPO_ACCESS_TOKEN }}
      # Docker options - https://docs.docker.com/reference/cli/docker/container/create/#options
      # ue4 user in the unreal engine container is uid 1000, gid 1000, has passwordless sudo
      options: --user root

    steps:
      - name: Set safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: AdventureGameTemplate checkout code
        uses: actions/checkout@v6.1.0
        with:
          lfs: true

      - name: PaperZD checkout code
        uses: actions/checkout@v6.1.0
        with:
          repository: heavybullets/PaperZD
          path: Plugins/PaperZD
          ref: v2.2.4
          
      - name: Build project
        run: |
          grep -q EngineVersion Plugins/PaperZD/PaperZD.uplugin && sed -i 's/"EngineVersion":.*/"EngineVersion": "5.6.0",/g' Plugins/PaperZD/PaperZD.uplugin
          ./Scripts/Build.sh

      - name: Tests
        run: |
          chown -R 1000:1000 $RUNNER_WORKSPACE
          su ue4 -c "/usr/bin/env GITHUB_WORKSPACE=$GITHUB_WORKSPACE ./Scripts/Test.sh"

      - name: Results
        uses: dorny/test-reporter@v3.0.0
        with:
          name: Unreal Engine Automation Tests
          path: Reports/*.json
          reporter: dart-json
          
          
          
