name: Unreal Engine Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:
    # Containers require a Linux-based runner host
    runs-on: ubuntu-latest
      
    container:
      image: ghcr.io/epicgames/unreal-engine:dev-slim-5.6.1
      credentials:
        username: ${{ secrets.GHCR_IO_USERNAME }}
        password: ${{ secrets.REPO_ACCESS_TOKEN }}
      options: --user root
      volumes:
        - /project

    steps:
      - name: AdventureGameTemplate checkout code
        uses: actions/checkout@v6.1.0
        with:
          lfs: true

      - name: PaperZD checkout code
        uses: actions/checkout@v6.1.0
        with:
          repository: heavybullets/PaperZD
          path: Plugins/PaperZD
          ref: v2.2.4

      - name: Build project
        run: |
          grep -q EngineVersion Plugins/PaperZD/PaperZD.uplugin && sed -i 's/"EngineVersion":.*/"EngineVersion": "5.6.0",/g' Plugins/PaperZD/PaperZD.uplugin
          /usr/bin/bash -x ./Scripts/Build.sh

      - name: Tests
        run: |
          sudo -u ue4 bash -c '/usr/bin/bash -x /project/Scripts/Test.sh'

      - name: Results
        uses: dorny/test-reporter@v3.0.0
        with:
          name: Unreal Engine Automation Tests
          path: Reports/*.json
          reporter: dart-json
          
          
          
